version: '3'
services:
  web:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    networks:
      - web
  app:
    image: php:7.2-fpm
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    networks:
      - web
networks:
  web: