version: '3'
services:
  web:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../html:/var/www/html
    networks:
      - web
  app:
    build: .
    image: boyz-app
    working_dir: /var/www/html
    volumes:
      - ../html:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_NAME
    networks:
      - web
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - web
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
    depends_on:
      - db
    networks:
      - web
networks:
  web: