version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../html:/var/www/html
  app:
    build: .
    image: boyz-app
    working_dir: /var/www/html
    environment:
      DB_HOST: db
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    volumes:
      - ../html:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    container_name: boyz-db
    volumes:
      - ./mysql/dumps:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: boyz-pma
    environment:
      PMA_HOST: db
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PMA_PMADB: $DB_NAME
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTH: $NGROK_TOKEN
      NGROK_REGION: eu
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
